/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ObjectTypeService } from "../objectType.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ObjectTypeCreateInput } from "./ObjectTypeCreateInput";
import { ObjectType } from "./ObjectType";
import { ObjectTypeFindManyArgs } from "./ObjectTypeFindManyArgs";
import { ObjectTypeWhereUniqueInput } from "./ObjectTypeWhereUniqueInput";
import { ObjectTypeUpdateInput } from "./ObjectTypeUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ObjectTypeControllerBase {
  constructor(
    protected readonly service: ObjectTypeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: ObjectType })
  @nestAccessControl.UseRoles({
    resource: "ObjectType",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createObjectType(
    @common.Body() data: ObjectTypeCreateInput
  ): Promise<ObjectType> {
    return await this.service.createObjectType({
      data: {
        ...data,

        PropertyTypes: {
          connect: data.PropertyTypes,
        },

        eventTypes: {
          connect: data.eventTypes,
        },
      },
      select: {
        PropertyTypes: {
          select: {
            id: true,
          },
        },

        createdAt: true,

        eventTypes: {
          select: {
            id: true,
          },
        },

        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [ObjectType] })
  @ApiNestedQuery(ObjectTypeFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ObjectType",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async objectTypes(@common.Req() request: Request): Promise<ObjectType[]> {
    const args = plainToClass(ObjectTypeFindManyArgs, request.query);
    return this.service.objectTypes({
      ...args,
      select: {
        PropertyTypes: {
          select: {
            id: true,
          },
        },

        createdAt: true,

        eventTypes: {
          select: {
            id: true,
          },
        },

        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: ObjectType })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ObjectType",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async objectType(
    @common.Param() params: ObjectTypeWhereUniqueInput
  ): Promise<ObjectType | null> {
    const result = await this.service.objectType({
      where: params,
      select: {
        PropertyTypes: {
          select: {
            id: true,
          },
        },

        createdAt: true,

        eventTypes: {
          select: {
            id: true,
          },
        },

        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: ObjectType })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ObjectType",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateObjectType(
    @common.Param() params: ObjectTypeWhereUniqueInput,
    @common.Body() data: ObjectTypeUpdateInput
  ): Promise<ObjectType | null> {
    try {
      return await this.service.updateObjectType({
        where: params,
        data: {
          ...data,

          PropertyTypes: {
            connect: data.PropertyTypes,
          },

          eventTypes: {
            connect: data.eventTypes,
          },
        },
        select: {
          PropertyTypes: {
            select: {
              id: true,
            },
          },

          createdAt: true,

          eventTypes: {
            select: {
              id: true,
            },
          },

          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: ObjectType })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "ObjectType",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteObjectType(
    @common.Param() params: ObjectTypeWhereUniqueInput
  ): Promise<ObjectType | null> {
    try {
      return await this.service.deleteObjectType({
        where: params,
        select: {
          PropertyTypes: {
            select: {
              id: true,
            },
          },

          createdAt: true,

          eventTypes: {
            select: {
              id: true,
            },
          },

          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
