/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  ObjectType as PrismaObjectType,
  PropertyType as PrismaPropertyType,
  EventType as PrismaEventType,
} from "@prisma/client";

export class ObjectTypeServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.ObjectTypeCountArgs, "select">
  ): Promise<number> {
    return this.prisma.objectType.count(args);
  }

  async objectTypes(
    args: Prisma.ObjectTypeFindManyArgs
  ): Promise<PrismaObjectType[]> {
    return this.prisma.objectType.findMany(args);
  }
  async objectType(
    args: Prisma.ObjectTypeFindUniqueArgs
  ): Promise<PrismaObjectType | null> {
    return this.prisma.objectType.findUnique(args);
  }
  async createObjectType(
    args: Prisma.ObjectTypeCreateArgs
  ): Promise<PrismaObjectType> {
    return this.prisma.objectType.create(args);
  }
  async updateObjectType(
    args: Prisma.ObjectTypeUpdateArgs
  ): Promise<PrismaObjectType> {
    return this.prisma.objectType.update(args);
  }
  async deleteObjectType(
    args: Prisma.ObjectTypeDeleteArgs
  ): Promise<PrismaObjectType> {
    return this.prisma.objectType.delete(args);
  }

  async getPropertyTypes(parentId: string): Promise<PrismaPropertyType | null> {
    return this.prisma.objectType
      .findUnique({
        where: { id: parentId },
      })
      .PropertyTypes();
  }

  async getEventTypes(parentId: string): Promise<PrismaEventType | null> {
    return this.prisma.objectType
      .findUnique({
        where: { id: parentId },
      })
      .eventTypes();
  }
}
