/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { ObjectType } from "./ObjectType";
import { ObjectTypeCountArgs } from "./ObjectTypeCountArgs";
import { ObjectTypeFindManyArgs } from "./ObjectTypeFindManyArgs";
import { ObjectTypeFindUniqueArgs } from "./ObjectTypeFindUniqueArgs";
import { CreateObjectTypeArgs } from "./CreateObjectTypeArgs";
import { UpdateObjectTypeArgs } from "./UpdateObjectTypeArgs";
import { DeleteObjectTypeArgs } from "./DeleteObjectTypeArgs";
import { PropertyType } from "../../propertyType/base/PropertyType";
import { EventType } from "../../eventType/base/EventType";
import { ObjectTypeService } from "../objectType.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => ObjectType)
export class ObjectTypeResolverBase {
  constructor(
    protected readonly service: ObjectTypeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "ObjectType",
    action: "read",
    possession: "any",
  })
  async _objectTypesMeta(
    @graphql.Args() args: ObjectTypeCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [ObjectType])
  @nestAccessControl.UseRoles({
    resource: "ObjectType",
    action: "read",
    possession: "any",
  })
  async objectTypes(
    @graphql.Args() args: ObjectTypeFindManyArgs
  ): Promise<ObjectType[]> {
    return this.service.objectTypes(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => ObjectType, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "ObjectType",
    action: "read",
    possession: "own",
  })
  async objectType(
    @graphql.Args() args: ObjectTypeFindUniqueArgs
  ): Promise<ObjectType | null> {
    const result = await this.service.objectType(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ObjectType)
  @nestAccessControl.UseRoles({
    resource: "ObjectType",
    action: "create",
    possession: "any",
  })
  async createObjectType(
    @graphql.Args() args: CreateObjectTypeArgs
  ): Promise<ObjectType> {
    return await this.service.createObjectType({
      ...args,
      data: {
        ...args.data,

        PropertyTypes: {
          connect: args.data.PropertyTypes,
        },

        eventTypes: {
          connect: args.data.eventTypes,
        },
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => ObjectType)
  @nestAccessControl.UseRoles({
    resource: "ObjectType",
    action: "update",
    possession: "any",
  })
  async updateObjectType(
    @graphql.Args() args: UpdateObjectTypeArgs
  ): Promise<ObjectType | null> {
    try {
      return await this.service.updateObjectType({
        ...args,
        data: {
          ...args.data,

          PropertyTypes: {
            connect: args.data.PropertyTypes,
          },

          eventTypes: {
            connect: args.data.eventTypes,
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => ObjectType)
  @nestAccessControl.UseRoles({
    resource: "ObjectType",
    action: "delete",
    possession: "any",
  })
  async deleteObjectType(
    @graphql.Args() args: DeleteObjectTypeArgs
  ): Promise<ObjectType | null> {
    try {
      return await this.service.deleteObjectType(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => PropertyType, {
    nullable: true,
    name: "propertyTypes",
  })
  @nestAccessControl.UseRoles({
    resource: "PropertyType",
    action: "read",
    possession: "any",
  })
  async getPropertyTypes(
    @graphql.Parent() parent: ObjectType
  ): Promise<PropertyType | null> {
    const result = await this.service.getPropertyTypes(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => EventType, {
    nullable: true,
    name: "eventTypes",
  })
  @nestAccessControl.UseRoles({
    resource: "EventType",
    action: "read",
    possession: "any",
  })
  async getEventTypes(
    @graphql.Parent() parent: ObjectType
  ): Promise<EventType | null> {
    const result = await this.service.getEventTypes(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
