/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { AssociationService } from "../association.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AssociationCreateInput } from "./AssociationCreateInput";
import { Association } from "./Association";
import { AssociationFindManyArgs } from "./AssociationFindManyArgs";
import { AssociationWhereUniqueInput } from "./AssociationWhereUniqueInput";
import { AssociationUpdateInput } from "./AssociationUpdateInput";
import { ObjectFindManyArgs } from "../../object/base/ObjectFindManyArgs";
import { Object } from "../../object/base/Object";
import { ObjectWhereUniqueInput } from "../../object/base/ObjectWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class AssociationControllerBase {
  constructor(
    protected readonly service: AssociationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Association })
  @nestAccessControl.UseRoles({
    resource: "Association",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createAssociation(
    @common.Body() data: AssociationCreateInput
  ): Promise<Association> {
    return await this.service.createAssociation({
      data: {
        ...data,

        associationType: data.associationType
          ? {
              connect: data.associationType,
            }
          : undefined,
      },
      select: {
        associationType: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        updatedAt: true,
        value: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Association] })
  @ApiNestedQuery(AssociationFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Association",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async associations(@common.Req() request: Request): Promise<Association[]> {
    const args = plainToClass(AssociationFindManyArgs, request.query);
    return this.service.associations({
      ...args,
      select: {
        associationType: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        updatedAt: true,
        value: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Association })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Association",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async association(
    @common.Param() params: AssociationWhereUniqueInput
  ): Promise<Association | null> {
    const result = await this.service.association({
      where: params,
      select: {
        associationType: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        updatedAt: true,
        value: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Association })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Association",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateAssociation(
    @common.Param() params: AssociationWhereUniqueInput,
    @common.Body() data: AssociationUpdateInput
  ): Promise<Association | null> {
    try {
      return await this.service.updateAssociation({
        where: params,
        data: {
          ...data,

          associationType: data.associationType
            ? {
                connect: data.associationType,
              }
            : undefined,
        },
        select: {
          associationType: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          updatedAt: true,
          value: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Association })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Association",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteAssociation(
    @common.Param() params: AssociationWhereUniqueInput
  ): Promise<Association | null> {
    try {
      return await this.service.deleteAssociation({
        where: params,
        select: {
          associationType: {
            select: {
              id: true,
            },
          },

          createdAt: true,
          id: true,
          updatedAt: true,
          value: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/object")
  @ApiNestedQuery(ObjectFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Object",
    action: "read",
    possession: "any",
  })
  async findObject(
    @common.Req() request: Request,
    @common.Param() params: AssociationWhereUniqueInput
  ): Promise<Object[]> {
    const query = plainToClass(ObjectFindManyArgs, request.query);
    const results = await this.service.findObject(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/object")
  @nestAccessControl.UseRoles({
    resource: "Association",
    action: "update",
    possession: "any",
  })
  async connectObject(
    @common.Param() params: AssociationWhereUniqueInput,
    @common.Body() body: ObjectWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      object: {
        connect: body,
      },
    };
    await this.service.updateAssociation({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/object")
  @nestAccessControl.UseRoles({
    resource: "Association",
    action: "update",
    possession: "any",
  })
  async updateObject(
    @common.Param() params: AssociationWhereUniqueInput,
    @common.Body() body: ObjectWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      object: {
        set: body,
      },
    };
    await this.service.updateAssociation({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/object")
  @nestAccessControl.UseRoles({
    resource: "Association",
    action: "update",
    possession: "any",
  })
  async disconnectObject(
    @common.Param() params: AssociationWhereUniqueInput,
    @common.Body() body: ObjectWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      object: {
        disconnect: body,
      },
    };
    await this.service.updateAssociation({
      where: params,
      data,
      select: { id: true },
    });
  }
}
