/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Association } from "./Association";
import { AssociationCountArgs } from "./AssociationCountArgs";
import { AssociationFindManyArgs } from "./AssociationFindManyArgs";
import { AssociationFindUniqueArgs } from "./AssociationFindUniqueArgs";
import { CreateAssociationArgs } from "./CreateAssociationArgs";
import { UpdateAssociationArgs } from "./UpdateAssociationArgs";
import { DeleteAssociationArgs } from "./DeleteAssociationArgs";
import { ObjectFindManyArgs } from "../../object/base/ObjectFindManyArgs";
import { Object } from "../../object/base/Object";
import { AssociationType } from "../../associationType/base/AssociationType";
import { AssociationService } from "../association.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Association)
export class AssociationResolverBase {
  constructor(
    protected readonly service: AssociationService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Association",
    action: "read",
    possession: "any",
  })
  async _associationsMeta(
    @graphql.Args() args: AssociationCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Association])
  @nestAccessControl.UseRoles({
    resource: "Association",
    action: "read",
    possession: "any",
  })
  async associations(
    @graphql.Args() args: AssociationFindManyArgs
  ): Promise<Association[]> {
    return this.service.associations(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Association, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Association",
    action: "read",
    possession: "own",
  })
  async association(
    @graphql.Args() args: AssociationFindUniqueArgs
  ): Promise<Association | null> {
    const result = await this.service.association(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Association)
  @nestAccessControl.UseRoles({
    resource: "Association",
    action: "create",
    possession: "any",
  })
  async createAssociation(
    @graphql.Args() args: CreateAssociationArgs
  ): Promise<Association> {
    return await this.service.createAssociation({
      ...args,
      data: {
        ...args.data,

        associationType: args.data.associationType
          ? {
              connect: args.data.associationType,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Association)
  @nestAccessControl.UseRoles({
    resource: "Association",
    action: "update",
    possession: "any",
  })
  async updateAssociation(
    @graphql.Args() args: UpdateAssociationArgs
  ): Promise<Association | null> {
    try {
      return await this.service.updateAssociation({
        ...args,
        data: {
          ...args.data,

          associationType: args.data.associationType
            ? {
                connect: args.data.associationType,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Association)
  @nestAccessControl.UseRoles({
    resource: "Association",
    action: "delete",
    possession: "any",
  })
  async deleteAssociation(
    @graphql.Args() args: DeleteAssociationArgs
  ): Promise<Association | null> {
    try {
      return await this.service.deleteAssociation(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Object], { name: "object" })
  @nestAccessControl.UseRoles({
    resource: "Object",
    action: "read",
    possession: "any",
  })
  async findObject(
    @graphql.Parent() parent: Association,
    @graphql.Args() args: ObjectFindManyArgs
  ): Promise<Object[]> {
    const results = await this.service.findObject(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => AssociationType, {
    nullable: true,
    name: "associationType",
  })
  @nestAccessControl.UseRoles({
    resource: "AssociationType",
    action: "read",
    possession: "any",
  })
  async getAssociationType(
    @graphql.Parent() parent: Association
  ): Promise<AssociationType | null> {
    const result = await this.service.getAssociationType(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
