/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  AssociationType as PrismaAssociationType,
  Association as PrismaAssociation,
} from "@prisma/client";

export class AssociationTypeServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.AssociationTypeCountArgs, "select">
  ): Promise<number> {
    return this.prisma.associationType.count(args);
  }

  async associationTypes(
    args: Prisma.AssociationTypeFindManyArgs
  ): Promise<PrismaAssociationType[]> {
    return this.prisma.associationType.findMany(args);
  }
  async associationType(
    args: Prisma.AssociationTypeFindUniqueArgs
  ): Promise<PrismaAssociationType | null> {
    return this.prisma.associationType.findUnique(args);
  }
  async createAssociationType(
    args: Prisma.AssociationTypeCreateArgs
  ): Promise<PrismaAssociationType> {
    return this.prisma.associationType.create(args);
  }
  async updateAssociationType(
    args: Prisma.AssociationTypeUpdateArgs
  ): Promise<PrismaAssociationType> {
    return this.prisma.associationType.update(args);
  }
  async deleteAssociationType(
    args: Prisma.AssociationTypeDeleteArgs
  ): Promise<PrismaAssociationType> {
    return this.prisma.associationType.delete(args);
  }

  async findAssociations(
    parentId: string,
    args: Prisma.AssociationFindManyArgs
  ): Promise<PrismaAssociation[]> {
    return this.prisma.associationType
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .associations(args);
  }
}
