/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AssociationType } from "./AssociationType";
import { AssociationTypeCountArgs } from "./AssociationTypeCountArgs";
import { AssociationTypeFindManyArgs } from "./AssociationTypeFindManyArgs";
import { AssociationTypeFindUniqueArgs } from "./AssociationTypeFindUniqueArgs";
import { CreateAssociationTypeArgs } from "./CreateAssociationTypeArgs";
import { UpdateAssociationTypeArgs } from "./UpdateAssociationTypeArgs";
import { DeleteAssociationTypeArgs } from "./DeleteAssociationTypeArgs";
import { AssociationFindManyArgs } from "../../association/base/AssociationFindManyArgs";
import { Association } from "../../association/base/Association";
import { AssociationTypeService } from "../associationType.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => AssociationType)
export class AssociationTypeResolverBase {
  constructor(
    protected readonly service: AssociationTypeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "AssociationType",
    action: "read",
    possession: "any",
  })
  async _associationTypesMeta(
    @graphql.Args() args: AssociationTypeCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [AssociationType])
  @nestAccessControl.UseRoles({
    resource: "AssociationType",
    action: "read",
    possession: "any",
  })
  async associationTypes(
    @graphql.Args() args: AssociationTypeFindManyArgs
  ): Promise<AssociationType[]> {
    return this.service.associationTypes(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => AssociationType, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "AssociationType",
    action: "read",
    possession: "own",
  })
  async associationType(
    @graphql.Args() args: AssociationTypeFindUniqueArgs
  ): Promise<AssociationType | null> {
    const result = await this.service.associationType(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => AssociationType)
  @nestAccessControl.UseRoles({
    resource: "AssociationType",
    action: "create",
    possession: "any",
  })
  async createAssociationType(
    @graphql.Args() args: CreateAssociationTypeArgs
  ): Promise<AssociationType> {
    return await this.service.createAssociationType({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => AssociationType)
  @nestAccessControl.UseRoles({
    resource: "AssociationType",
    action: "update",
    possession: "any",
  })
  async updateAssociationType(
    @graphql.Args() args: UpdateAssociationTypeArgs
  ): Promise<AssociationType | null> {
    try {
      return await this.service.updateAssociationType({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => AssociationType)
  @nestAccessControl.UseRoles({
    resource: "AssociationType",
    action: "delete",
    possession: "any",
  })
  async deleteAssociationType(
    @graphql.Args() args: DeleteAssociationTypeArgs
  ): Promise<AssociationType | null> {
    try {
      return await this.service.deleteAssociationType(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Association], { name: "associations" })
  @nestAccessControl.UseRoles({
    resource: "Association",
    action: "read",
    possession: "any",
  })
  async findAssociations(
    @graphql.Parent() parent: AssociationType,
    @graphql.Args() args: AssociationFindManyArgs
  ): Promise<Association[]> {
    const results = await this.service.findAssociations(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
