/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { AssociationTypeService } from "../associationType.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AssociationTypeCreateInput } from "./AssociationTypeCreateInput";
import { AssociationType } from "./AssociationType";
import { AssociationTypeFindManyArgs } from "./AssociationTypeFindManyArgs";
import { AssociationTypeWhereUniqueInput } from "./AssociationTypeWhereUniqueInput";
import { AssociationTypeUpdateInput } from "./AssociationTypeUpdateInput";
import { AssociationFindManyArgs } from "../../association/base/AssociationFindManyArgs";
import { Association } from "../../association/base/Association";
import { AssociationWhereUniqueInput } from "../../association/base/AssociationWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class AssociationTypeControllerBase {
  constructor(
    protected readonly service: AssociationTypeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: AssociationType })
  @nestAccessControl.UseRoles({
    resource: "AssociationType",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createAssociationType(
    @common.Body() data: AssociationTypeCreateInput
  ): Promise<AssociationType> {
    return await this.service.createAssociationType({
      data: data,
      select: {
        createdAt: true,
        id: true,
        schema: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [AssociationType] })
  @ApiNestedQuery(AssociationTypeFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "AssociationType",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async associationTypes(
    @common.Req() request: Request
  ): Promise<AssociationType[]> {
    const args = plainToClass(AssociationTypeFindManyArgs, request.query);
    return this.service.associationTypes({
      ...args,
      select: {
        createdAt: true,
        id: true,
        schema: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: AssociationType })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AssociationType",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async associationType(
    @common.Param() params: AssociationTypeWhereUniqueInput
  ): Promise<AssociationType | null> {
    const result = await this.service.associationType({
      where: params,
      select: {
        createdAt: true,
        id: true,
        schema: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: AssociationType })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AssociationType",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateAssociationType(
    @common.Param() params: AssociationTypeWhereUniqueInput,
    @common.Body() data: AssociationTypeUpdateInput
  ): Promise<AssociationType | null> {
    try {
      return await this.service.updateAssociationType({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          schema: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: AssociationType })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "AssociationType",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteAssociationType(
    @common.Param() params: AssociationTypeWhereUniqueInput
  ): Promise<AssociationType | null> {
    try {
      return await this.service.deleteAssociationType({
        where: params,
        select: {
          createdAt: true,
          id: true,
          schema: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/associations")
  @ApiNestedQuery(AssociationFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Association",
    action: "read",
    possession: "any",
  })
  async findAssociations(
    @common.Req() request: Request,
    @common.Param() params: AssociationTypeWhereUniqueInput
  ): Promise<Association[]> {
    const query = plainToClass(AssociationFindManyArgs, request.query);
    const results = await this.service.findAssociations(params.id, {
      ...query,
      select: {
        associationType: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        updatedAt: true,
        value: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/associations")
  @nestAccessControl.UseRoles({
    resource: "AssociationType",
    action: "update",
    possession: "any",
  })
  async connectAssociations(
    @common.Param() params: AssociationTypeWhereUniqueInput,
    @common.Body() body: AssociationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      associations: {
        connect: body,
      },
    };
    await this.service.updateAssociationType({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/associations")
  @nestAccessControl.UseRoles({
    resource: "AssociationType",
    action: "update",
    possession: "any",
  })
  async updateAssociations(
    @common.Param() params: AssociationTypeWhereUniqueInput,
    @common.Body() body: AssociationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      associations: {
        set: body,
      },
    };
    await this.service.updateAssociationType({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/associations")
  @nestAccessControl.UseRoles({
    resource: "AssociationType",
    action: "update",
    possession: "any",
  })
  async disconnectAssociations(
    @common.Param() params: AssociationTypeWhereUniqueInput,
    @common.Body() body: AssociationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      associations: {
        disconnect: body,
      },
    };
    await this.service.updateAssociationType({
      where: params,
      data,
      select: { id: true },
    });
  }
}
