using Fret.APIs.Dtos;
using Fret.Infrastructure.Models;

namespace Fret.APIs.Extensions;

public static class LinesExtensions
{
    public static Line ToDto(this LineDbModel model)
    {
        return new Line
        {
            AdresseAffrTeurSlotteur = model.AdresseAffrTeurSlotteur,
            AdresseDeLExpDiteur = model.AdresseDeLExpDiteur,
            AdresseDeLExportateur = model.AdresseDeLExportateur,
            AdresseDeLaPartieNotifier = model.AdresseDeLaPartieNotifier,
            AdresseDuDestinataire = model.AdresseDuDestinataire,
            AffrTeurDEspaceSlot = model.AffrTeurDEspaceSlot,
            ArticleMontantCodeDeDevise = model.ArticleMontantCodeDeDevise,
            CabotageOn = model.CabotageOn,
            CodeDeCatGorieDeBl = model.CodeDeCatGorieDeBl,
            CodeDeCatGorieDeRectificationDeBl = model.CodeDeCatGorieDeRectificationDeBl,
            CodeDeClasseUndg = model.CodeDeClasseUndg,
            CodeDeGroupeur = model.CodeDeGroupeur,
            CodeDeLUnitDeColis = model.CodeDeLUnitDeColis,
            CodeDeLieuDeChargement = model.CodeDeLieuDeChargement,
            CodeDeLieuDeDChargement = model.CodeDeLieuDeDChargement,
            CodeDeRGionDeTransbordement = model.CodeDeRGionDeTransbordement,
            CodeDeStevedoremanutentionnaire = model.CodeDeStevedoremanutentionnaire,
            CodeDeTypeDHydrocarbure = model.CodeDeTypeDHydrocarbure,
            CodeDeTypeDeBl = model.CodeDeTypeDeBl,
            CodeDeZoneSousDouane = model.CodeDeZoneSousDouane,
            CodeSh = model.CodeSh,
            CreatedAt = model.CreatedAt,
            Crn = model.Crn,
            CrnPrCDent = model.CrnPrCDent,
            DChargementOn = model.DChargementOn,
            DateEmissionBl = model.DateEmissionBl,
            DateEtHeureDeModificationFinale = model.DateEtHeureDeModificationFinale,
            DateEtHeureDePremierEnregistrement = model.DateEtHeureDePremierEnregistrement,
            EMailDeDestinataire = model.EMailDeDestinataire,
            EmailDeLExpDiteur = model.EmailDeLExpDiteur,
            EmailDeLExportateur = model.EmailDeLExportateur,
            EmailDeLaPartieNotifier = model.EmailDeLaPartieNotifier,
            Hsn = model.Hsn,
            Id = model.Id,
            IdDuModificateurFinal = model.IdDuModificateurFinal,
            IdDuPremierEnregistrant = model.IdDuPremierEnregistrant,
            IdentifiantUndg = model.IdentifiantUndg,
            IndFretPrPayD = model.IndFretPrPayD,
            InfoSupplMentaire = model.InfoSupplMentaire,
            MarqueDeColis = model.MarqueDeColis,
            ModeDeLivraison = model.ModeDeLivraison,
            Msn = model.Msn,
            NDeBl = model.NDeBl,
            NDeHouseBl = model.NDeHouseBl,
            NDeSQuenceDeBl = model.NDeSQuenceDeBl,
            NDeTlPhoneDeDestinataire = model.NDeTlPhoneDeDestinataire,
            NatureDeCargaison = model.NatureDeCargaison,
            NatureDeMarchandise = model.NatureDeMarchandise,
            NifDeDStinataire = model.NifDeDStinataire,
            NifDeLExportateur = model.NifDeLExportateur,
            NinDExportateur = model.NinDExportateur,
            NinDeDStinataire = model.NinDeDStinataire,
            NomDeDestinataire = model.NomDeDestinataire,
            NomDeLAffrTeurSlotteur = model.NomDeLAffrTeurSlotteur,
            NomDeLArticle = model.NomDeLArticle,
            NomDeLExpDiteur = model.NomDeLExpDiteur,
            NomDeLExportateur = model.NomDeLExportateur,
            NomDeLaPartieNotifier = model.NomDeLaPartieNotifier,
            NombreDeColis = model.NombreDeColis,
            NombreDeConteneurs = model.NombreDeConteneurs,
            NombreDeVHicules = model.NombreDeVHicules,
            NombreTotalDeSousBl = model.NombreTotalDeSousBl,
            NumRoDeGestionDeLEnregistrementDeLaDClarationDeFret =
                model.NumRoDeGestionDeLEnregistrementDeLaDClarationDeFret,
            NumeroCas = model.NumeroCas,
            PoidsBrut = model.PoidsBrut,
            PoidsNet = model.PoidsNet,
            SuppressionOn = model.SuppressionOn,
            TLPhoneDeLExpDiteur = model.TLPhoneDeLExpDiteur,
            TLPhoneDeLExportateur = model.TLPhoneDeLExportateur,
            TLPhoneDeLaPartieNotifier = model.TLPhoneDeLaPartieNotifier,
            TareDeConteneurSVide = model.TareDeConteneurSVide,
            TypeDeFlux = model.TypeDeFlux,
            UpdatedAt = model.UpdatedAt,
            ValeurDeMarchandise = model.ValeurDeMarchandise,
            VolumeLitre = model.VolumeLitre,
            VolumeMtq = model.VolumeMtq,
        };
    }

    public static LineDbModel ToModel(this LineUpdateInput updateDto, LineWhereUniqueInput uniqueId)
    {
        var line = new LineDbModel
        {
            Id = uniqueId.Id,
            AdresseAffrTeurSlotteur = updateDto.AdresseAffrTeurSlotteur,
            AdresseDeLExpDiteur = updateDto.AdresseDeLExpDiteur,
            AdresseDeLExportateur = updateDto.AdresseDeLExportateur,
            AdresseDeLaPartieNotifier = updateDto.AdresseDeLaPartieNotifier,
            AdresseDuDestinataire = updateDto.AdresseDuDestinataire,
            AffrTeurDEspaceSlot = updateDto.AffrTeurDEspaceSlot,
            ArticleMontantCodeDeDevise = updateDto.ArticleMontantCodeDeDevise,
            CabotageOn = updateDto.CabotageOn,
            CodeDeCatGorieDeBl = updateDto.CodeDeCatGorieDeBl,
            CodeDeCatGorieDeRectificationDeBl = updateDto.CodeDeCatGorieDeRectificationDeBl,
            CodeDeClasseUndg = updateDto.CodeDeClasseUndg,
            CodeDeGroupeur = updateDto.CodeDeGroupeur,
            CodeDeLUnitDeColis = updateDto.CodeDeLUnitDeColis,
            CodeDeLieuDeChargement = updateDto.CodeDeLieuDeChargement,
            CodeDeLieuDeDChargement = updateDto.CodeDeLieuDeDChargement,
            CodeDeRGionDeTransbordement = updateDto.CodeDeRGionDeTransbordement,
            CodeDeStevedoremanutentionnaire = updateDto.CodeDeStevedoremanutentionnaire,
            CodeDeTypeDHydrocarbure = updateDto.CodeDeTypeDHydrocarbure,
            CodeDeTypeDeBl = updateDto.CodeDeTypeDeBl,
            CodeDeZoneSousDouane = updateDto.CodeDeZoneSousDouane,
            CodeSh = updateDto.CodeSh,
            Crn = updateDto.Crn,
            CrnPrCDent = updateDto.CrnPrCDent,
            DChargementOn = updateDto.DChargementOn,
            DateEmissionBl = updateDto.DateEmissionBl,
            DateEtHeureDeModificationFinale = updateDto.DateEtHeureDeModificationFinale,
            DateEtHeureDePremierEnregistrement = updateDto.DateEtHeureDePremierEnregistrement,
            EMailDeDestinataire = updateDto.EMailDeDestinataire,
            EmailDeLExpDiteur = updateDto.EmailDeLExpDiteur,
            EmailDeLExportateur = updateDto.EmailDeLExportateur,
            EmailDeLaPartieNotifier = updateDto.EmailDeLaPartieNotifier,
            Hsn = updateDto.Hsn,
            IdDuModificateurFinal = updateDto.IdDuModificateurFinal,
            IdDuPremierEnregistrant = updateDto.IdDuPremierEnregistrant,
            IdentifiantUndg = updateDto.IdentifiantUndg,
            IndFretPrPayD = updateDto.IndFretPrPayD,
            InfoSupplMentaire = updateDto.InfoSupplMentaire,
            MarqueDeColis = updateDto.MarqueDeColis,
            ModeDeLivraison = updateDto.ModeDeLivraison,
            Msn = updateDto.Msn,
            NDeBl = updateDto.NDeBl,
            NDeHouseBl = updateDto.NDeHouseBl,
            NDeSQuenceDeBl = updateDto.NDeSQuenceDeBl,
            NDeTlPhoneDeDestinataire = updateDto.NDeTlPhoneDeDestinataire,
            NatureDeCargaison = updateDto.NatureDeCargaison,
            NatureDeMarchandise = updateDto.NatureDeMarchandise,
            NifDeDStinataire = updateDto.NifDeDStinataire,
            NifDeLExportateur = updateDto.NifDeLExportateur,
            NinDExportateur = updateDto.NinDExportateur,
            NinDeDStinataire = updateDto.NinDeDStinataire,
            NomDeDestinataire = updateDto.NomDeDestinataire,
            NomDeLAffrTeurSlotteur = updateDto.NomDeLAffrTeurSlotteur,
            NomDeLArticle = updateDto.NomDeLArticle,
            NomDeLExpDiteur = updateDto.NomDeLExpDiteur,
            NomDeLExportateur = updateDto.NomDeLExportateur,
            NomDeLaPartieNotifier = updateDto.NomDeLaPartieNotifier,
            NombreDeColis = updateDto.NombreDeColis,
            NombreDeConteneurs = updateDto.NombreDeConteneurs,
            NombreDeVHicules = updateDto.NombreDeVHicules,
            NombreTotalDeSousBl = updateDto.NombreTotalDeSousBl,
            NumRoDeGestionDeLEnregistrementDeLaDClarationDeFret =
                updateDto.NumRoDeGestionDeLEnregistrementDeLaDClarationDeFret,
            NumeroCas = updateDto.NumeroCas,
            PoidsBrut = updateDto.PoidsBrut,
            PoidsNet = updateDto.PoidsNet,
            SuppressionOn = updateDto.SuppressionOn,
            TLPhoneDeLExpDiteur = updateDto.TLPhoneDeLExpDiteur,
            TLPhoneDeLExportateur = updateDto.TLPhoneDeLExportateur,
            TLPhoneDeLaPartieNotifier = updateDto.TLPhoneDeLaPartieNotifier,
            TareDeConteneurSVide = updateDto.TareDeConteneurSVide,
            TypeDeFlux = updateDto.TypeDeFlux,
            ValeurDeMarchandise = updateDto.ValeurDeMarchandise,
            VolumeLitre = updateDto.VolumeLitre,
            VolumeMtq = updateDto.VolumeMtq
        };

        if (updateDto.CreatedAt != null)
        {
            line.CreatedAt = updateDto.CreatedAt.Value;
        }
        if (updateDto.UpdatedAt != null)
        {
            line.UpdatedAt = updateDto.UpdatedAt.Value;
        }

        return line;
    }
}
