/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Object } from "./Object";
import { ObjectCountArgs } from "./ObjectCountArgs";
import { ObjectFindManyArgs } from "./ObjectFindManyArgs";
import { ObjectFindUniqueArgs } from "./ObjectFindUniqueArgs";
import { CreateObjectArgs } from "./CreateObjectArgs";
import { UpdateObjectArgs } from "./UpdateObjectArgs";
import { DeleteObjectArgs } from "./DeleteObjectArgs";
import { PropertyFindManyArgs } from "../../property/base/PropertyFindManyArgs";
import { Property } from "../../property/base/Property";
import { ActionFindManyArgs } from "../../action/base/ActionFindManyArgs";
import { Action } from "../../action/base/Action";
import { AssociationFindManyArgs } from "../../association/base/AssociationFindManyArgs";
import { Association } from "../../association/base/Association";
import { ObjectService } from "../object.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Object)
export class ObjectResolverBase {
  constructor(
    protected readonly service: ObjectService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Object",
    action: "read",
    possession: "any",
  })
  async _objectsMeta(
    @graphql.Args() args: ObjectCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Object])
  @nestAccessControl.UseRoles({
    resource: "Object",
    action: "read",
    possession: "any",
  })
  async objects(@graphql.Args() args: ObjectFindManyArgs): Promise<Object[]> {
    return this.service.objects(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Object, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Object",
    action: "read",
    possession: "own",
  })
  async object(
    @graphql.Args() args: ObjectFindUniqueArgs
  ): Promise<Object | null> {
    const result = await this.service.object(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Object)
  @nestAccessControl.UseRoles({
    resource: "Object",
    action: "create",
    possession: "any",
  })
  async createObject(@graphql.Args() args: CreateObjectArgs): Promise<Object> {
    return await this.service.createObject({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Object)
  @nestAccessControl.UseRoles({
    resource: "Object",
    action: "update",
    possession: "any",
  })
  async updateObject(
    @graphql.Args() args: UpdateObjectArgs
  ): Promise<Object | null> {
    try {
      return await this.service.updateObject({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Object)
  @nestAccessControl.UseRoles({
    resource: "Object",
    action: "delete",
    possession: "any",
  })
  async deleteObject(
    @graphql.Args() args: DeleteObjectArgs
  ): Promise<Object | null> {
    try {
      return await this.service.deleteObject(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Property], { name: "properties" })
  @nestAccessControl.UseRoles({
    resource: "Property",
    action: "read",
    possession: "any",
  })
  async findProperties(
    @graphql.Parent() parent: Object,
    @graphql.Args() args: PropertyFindManyArgs
  ): Promise<Property[]> {
    const results = await this.service.findProperties(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Action], { name: "actions" })
  @nestAccessControl.UseRoles({
    resource: "Action",
    action: "read",
    possession: "any",
  })
  async findActions(
    @graphql.Parent() parent: Object,
    @graphql.Args() args: ActionFindManyArgs
  ): Promise<Action[]> {
    const results = await this.service.findActions(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Association], { name: "associations" })
  @nestAccessControl.UseRoles({
    resource: "Association",
    action: "read",
    possession: "any",
  })
  async findAssociations(
    @graphql.Parent() parent: Object,
    @graphql.Args() args: AssociationFindManyArgs
  ): Promise<Association[]> {
    const results = await this.service.findAssociations(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
