/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { ObjectService } from "../object.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { ObjectCreateInput } from "./ObjectCreateInput";
import { Object } from "./Object";
import { ObjectFindManyArgs } from "./ObjectFindManyArgs";
import { ObjectWhereUniqueInput } from "./ObjectWhereUniqueInput";
import { ObjectUpdateInput } from "./ObjectUpdateInput";
import { PropertyFindManyArgs } from "../../property/base/PropertyFindManyArgs";
import { Property } from "../../property/base/Property";
import { PropertyWhereUniqueInput } from "../../property/base/PropertyWhereUniqueInput";
import { ActionFindManyArgs } from "../../action/base/ActionFindManyArgs";
import { Action } from "../../action/base/Action";
import { ActionWhereUniqueInput } from "../../action/base/ActionWhereUniqueInput";
import { AssociationFindManyArgs } from "../../association/base/AssociationFindManyArgs";
import { Association } from "../../association/base/Association";
import { AssociationWhereUniqueInput } from "../../association/base/AssociationWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class ObjectControllerBase {
  constructor(
    protected readonly service: ObjectService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Object })
  @nestAccessControl.UseRoles({
    resource: "Object",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createObject(@common.Body() data: ObjectCreateInput): Promise<Object> {
    return await this.service.createObject({
      data: data,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Object] })
  @ApiNestedQuery(ObjectFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Object",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async objects(@common.Req() request: Request): Promise<Object[]> {
    const args = plainToClass(ObjectFindManyArgs, request.query);
    return this.service.objects({
      ...args,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Object })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Object",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async object(
    @common.Param() params: ObjectWhereUniqueInput
  ): Promise<Object | null> {
    const result = await this.service.object({
      where: params,
      select: {
        createdAt: true,
        id: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Object })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Object",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateObject(
    @common.Param() params: ObjectWhereUniqueInput,
    @common.Body() data: ObjectUpdateInput
  ): Promise<Object | null> {
    try {
      return await this.service.updateObject({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Object })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Object",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteObject(
    @common.Param() params: ObjectWhereUniqueInput
  ): Promise<Object | null> {
    try {
      return await this.service.deleteObject({
        where: params,
        select: {
          createdAt: true,
          id: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/Properties")
  @ApiNestedQuery(PropertyFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Property",
    action: "read",
    possession: "any",
  })
  async findProperties(
    @common.Req() request: Request,
    @common.Param() params: ObjectWhereUniqueInput
  ): Promise<Property[]> {
    const query = plainToClass(PropertyFindManyArgs, request.query);
    const results = await this.service.findProperties(params.id, {
      ...query,
      select: {
        createdAt: true,

        dynamicProperty: {
          select: {
            id: true,
          },
        },

        id: true,

        object: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        value: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/Properties")
  @nestAccessControl.UseRoles({
    resource: "Object",
    action: "update",
    possession: "any",
  })
  async connectProperties(
    @common.Param() params: ObjectWhereUniqueInput,
    @common.Body() body: PropertyWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      Properties: {
        connect: body,
      },
    };
    await this.service.updateObject({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/Properties")
  @nestAccessControl.UseRoles({
    resource: "Object",
    action: "update",
    possession: "any",
  })
  async updateProperties(
    @common.Param() params: ObjectWhereUniqueInput,
    @common.Body() body: PropertyWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      Properties: {
        set: body,
      },
    };
    await this.service.updateObject({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/Properties")
  @nestAccessControl.UseRoles({
    resource: "Object",
    action: "update",
    possession: "any",
  })
  async disconnectProperties(
    @common.Param() params: ObjectWhereUniqueInput,
    @common.Body() body: PropertyWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      Properties: {
        disconnect: body,
      },
    };
    await this.service.updateObject({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/actions")
  @ApiNestedQuery(ActionFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Action",
    action: "read",
    possession: "any",
  })
  async findActions(
    @common.Req() request: Request,
    @common.Param() params: ObjectWhereUniqueInput
  ): Promise<Action[]> {
    const query = plainToClass(ActionFindManyArgs, request.query);
    const results = await this.service.findActions(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,

        object: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/actions")
  @nestAccessControl.UseRoles({
    resource: "Object",
    action: "update",
    possession: "any",
  })
  async connectActions(
    @common.Param() params: ObjectWhereUniqueInput,
    @common.Body() body: ActionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      actions: {
        connect: body,
      },
    };
    await this.service.updateObject({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/actions")
  @nestAccessControl.UseRoles({
    resource: "Object",
    action: "update",
    possession: "any",
  })
  async updateActions(
    @common.Param() params: ObjectWhereUniqueInput,
    @common.Body() body: ActionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      actions: {
        set: body,
      },
    };
    await this.service.updateObject({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/actions")
  @nestAccessControl.UseRoles({
    resource: "Object",
    action: "update",
    possession: "any",
  })
  async disconnectActions(
    @common.Param() params: ObjectWhereUniqueInput,
    @common.Body() body: ActionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      actions: {
        disconnect: body,
      },
    };
    await this.service.updateObject({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/associations")
  @ApiNestedQuery(AssociationFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Association",
    action: "read",
    possession: "any",
  })
  async findAssociations(
    @common.Req() request: Request,
    @common.Param() params: ObjectWhereUniqueInput
  ): Promise<Association[]> {
    const query = plainToClass(AssociationFindManyArgs, request.query);
    const results = await this.service.findAssociations(params.id, {
      ...query,
      select: {
        associationType: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        updatedAt: true,
        value: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/associations")
  @nestAccessControl.UseRoles({
    resource: "Object",
    action: "update",
    possession: "any",
  })
  async connectAssociations(
    @common.Param() params: ObjectWhereUniqueInput,
    @common.Body() body: AssociationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      associations: {
        connect: body,
      },
    };
    await this.service.updateObject({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/associations")
  @nestAccessControl.UseRoles({
    resource: "Object",
    action: "update",
    possession: "any",
  })
  async updateAssociations(
    @common.Param() params: ObjectWhereUniqueInput,
    @common.Body() body: AssociationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      associations: {
        set: body,
      },
    };
    await this.service.updateObject({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/associations")
  @nestAccessControl.UseRoles({
    resource: "Object",
    action: "update",
    possession: "any",
  })
  async disconnectAssociations(
    @common.Param() params: ObjectWhereUniqueInput,
    @common.Body() body: AssociationWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      associations: {
        disconnect: body,
      },
    };
    await this.service.updateObject({
      where: params,
      data,
      select: { id: true },
    });
  }
}
