/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import {
  Prisma,
  Step as PrismaStep,
  Task as PrismaTask,
  Workflow as PrismaWorkflow,
} from "@prisma/client";

export class StepServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(args: Omit<Prisma.StepCountArgs, "select">): Promise<number> {
    return this.prisma.step.count(args);
  }

  async steps(args: Prisma.StepFindManyArgs): Promise<PrismaStep[]> {
    return this.prisma.step.findMany(args);
  }
  async step(args: Prisma.StepFindUniqueArgs): Promise<PrismaStep | null> {
    return this.prisma.step.findUnique(args);
  }
  async createStep(args: Prisma.StepCreateArgs): Promise<PrismaStep> {
    return this.prisma.step.create(args);
  }
  async updateStep(args: Prisma.StepUpdateArgs): Promise<PrismaStep> {
    return this.prisma.step.update(args);
  }
  async deleteStep(args: Prisma.StepDeleteArgs): Promise<PrismaStep> {
    return this.prisma.step.delete(args);
  }

  async findTasks(
    parentId: string,
    args: Prisma.TaskFindManyArgs
  ): Promise<PrismaTask[]> {
    return this.prisma.step
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .tasks(args);
  }

  async getWorkflow(parentId: string): Promise<PrismaWorkflow | null> {
    return this.prisma.step
      .findUnique({
        where: { id: parentId },
      })
      .workflow();
  }
}
