/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { StepService } from "../step.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { StepCreateInput } from "./StepCreateInput";
import { Step } from "./Step";
import { StepFindManyArgs } from "./StepFindManyArgs";
import { StepWhereUniqueInput } from "./StepWhereUniqueInput";
import { StepUpdateInput } from "./StepUpdateInput";
import { TaskFindManyArgs } from "../../task/base/TaskFindManyArgs";
import { Task } from "../../task/base/Task";
import { TaskWhereUniqueInput } from "../../task/base/TaskWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class StepControllerBase {
  constructor(
    protected readonly service: StepService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Step })
  @nestAccessControl.UseRoles({
    resource: "Step",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createStep(@common.Body() data: StepCreateInput): Promise<Step> {
    return await this.service.createStep({
      data: {
        ...data,

        workflow: data.workflow
          ? {
              connect: data.workflow,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        id: true,
        kind: true,
        updatedAt: true,

        workflow: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Step] })
  @ApiNestedQuery(StepFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Step",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async steps(@common.Req() request: Request): Promise<Step[]> {
    const args = plainToClass(StepFindManyArgs, request.query);
    return this.service.steps({
      ...args,
      select: {
        createdAt: true,
        id: true,
        kind: true,
        updatedAt: true,

        workflow: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Step })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Step",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async step(
    @common.Param() params: StepWhereUniqueInput
  ): Promise<Step | null> {
    const result = await this.service.step({
      where: params,
      select: {
        createdAt: true,
        id: true,
        kind: true,
        updatedAt: true,

        workflow: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Step })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Step",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateStep(
    @common.Param() params: StepWhereUniqueInput,
    @common.Body() data: StepUpdateInput
  ): Promise<Step | null> {
    try {
      return await this.service.updateStep({
        where: params,
        data: {
          ...data,

          workflow: data.workflow
            ? {
                connect: data.workflow,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          id: true,
          kind: true,
          updatedAt: true,

          workflow: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Step })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Step",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteStep(
    @common.Param() params: StepWhereUniqueInput
  ): Promise<Step | null> {
    try {
      return await this.service.deleteStep({
        where: params,
        select: {
          createdAt: true,
          id: true,
          kind: true,
          updatedAt: true,

          workflow: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/tasks")
  @ApiNestedQuery(TaskFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Task",
    action: "read",
    possession: "any",
  })
  async findTasks(
    @common.Req() request: Request,
    @common.Param() params: StepWhereUniqueInput
  ): Promise<Task[]> {
    const query = plainToClass(TaskFindManyArgs, request.query);
    const results = await this.service.findTasks(params.id, {
      ...query,
      select: {
        action: {
          select: {
            id: true,
          },
        },

        context: true,
        createdAt: true,
        id: true,
        kind: true,

        step: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/tasks")
  @nestAccessControl.UseRoles({
    resource: "Step",
    action: "update",
    possession: "any",
  })
  async connectTasks(
    @common.Param() params: StepWhereUniqueInput,
    @common.Body() body: TaskWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      tasks: {
        connect: body,
      },
    };
    await this.service.updateStep({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/tasks")
  @nestAccessControl.UseRoles({
    resource: "Step",
    action: "update",
    possession: "any",
  })
  async updateTasks(
    @common.Param() params: StepWhereUniqueInput,
    @common.Body() body: TaskWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      tasks: {
        set: body,
      },
    };
    await this.service.updateStep({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/tasks")
  @nestAccessControl.UseRoles({
    resource: "Step",
    action: "update",
    possession: "any",
  })
  async disconnectTasks(
    @common.Param() params: StepWhereUniqueInput,
    @common.Body() body: TaskWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      tasks: {
        disconnect: body,
      },
    };
    await this.service.updateStep({
      where: params,
      data,
      select: { id: true },
    });
  }
}
