/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { Step } from "./Step";
import { StepCountArgs } from "./StepCountArgs";
import { StepFindManyArgs } from "./StepFindManyArgs";
import { StepFindUniqueArgs } from "./StepFindUniqueArgs";
import { CreateStepArgs } from "./CreateStepArgs";
import { UpdateStepArgs } from "./UpdateStepArgs";
import { DeleteStepArgs } from "./DeleteStepArgs";
import { TaskFindManyArgs } from "../../task/base/TaskFindManyArgs";
import { Task } from "../../task/base/Task";
import { Workflow } from "../../workflow/base/Workflow";
import { StepService } from "../step.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => Step)
export class StepResolverBase {
  constructor(
    protected readonly service: StepService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "Step",
    action: "read",
    possession: "any",
  })
  async _stepsMeta(
    @graphql.Args() args: StepCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [Step])
  @nestAccessControl.UseRoles({
    resource: "Step",
    action: "read",
    possession: "any",
  })
  async steps(@graphql.Args() args: StepFindManyArgs): Promise<Step[]> {
    return this.service.steps(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => Step, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "Step",
    action: "read",
    possession: "own",
  })
  async step(@graphql.Args() args: StepFindUniqueArgs): Promise<Step | null> {
    const result = await this.service.step(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Step)
  @nestAccessControl.UseRoles({
    resource: "Step",
    action: "create",
    possession: "any",
  })
  async createStep(@graphql.Args() args: CreateStepArgs): Promise<Step> {
    return await this.service.createStep({
      ...args,
      data: {
        ...args.data,

        workflow: args.data.workflow
          ? {
              connect: args.data.workflow,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => Step)
  @nestAccessControl.UseRoles({
    resource: "Step",
    action: "update",
    possession: "any",
  })
  async updateStep(@graphql.Args() args: UpdateStepArgs): Promise<Step | null> {
    try {
      return await this.service.updateStep({
        ...args,
        data: {
          ...args.data,

          workflow: args.data.workflow
            ? {
                connect: args.data.workflow,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => Step)
  @nestAccessControl.UseRoles({
    resource: "Step",
    action: "delete",
    possession: "any",
  })
  async deleteStep(@graphql.Args() args: DeleteStepArgs): Promise<Step | null> {
    try {
      return await this.service.deleteStep(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Task], { name: "tasks" })
  @nestAccessControl.UseRoles({
    resource: "Task",
    action: "read",
    possession: "any",
  })
  async findTasks(
    @graphql.Parent() parent: Step,
    @graphql.Args() args: TaskFindManyArgs
  ): Promise<Task[]> {
    const results = await this.service.findTasks(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Workflow, {
    nullable: true,
    name: "workflow",
  })
  @nestAccessControl.UseRoles({
    resource: "Workflow",
    action: "read",
    possession: "any",
  })
  async getWorkflow(@graphql.Parent() parent: Step): Promise<Workflow | null> {
    const result = await this.service.getWorkflow(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
