/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { PropertyType } from "./PropertyType";
import { PropertyTypeCountArgs } from "./PropertyTypeCountArgs";
import { PropertyTypeFindManyArgs } from "./PropertyTypeFindManyArgs";
import { PropertyTypeFindUniqueArgs } from "./PropertyTypeFindUniqueArgs";
import { CreatePropertyTypeArgs } from "./CreatePropertyTypeArgs";
import { UpdatePropertyTypeArgs } from "./UpdatePropertyTypeArgs";
import { DeletePropertyTypeArgs } from "./DeletePropertyTypeArgs";
import { PropertyFindManyArgs } from "../../property/base/PropertyFindManyArgs";
import { Property } from "../../property/base/Property";
import { ObjectTypeFindManyArgs } from "../../objectType/base/ObjectTypeFindManyArgs";
import { ObjectType } from "../../objectType/base/ObjectType";
import { PropertyTypeService } from "../propertyType.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => PropertyType)
export class PropertyTypeResolverBase {
  constructor(
    protected readonly service: PropertyTypeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "PropertyType",
    action: "read",
    possession: "any",
  })
  async _propertyTypesMeta(
    @graphql.Args() args: PropertyTypeCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [PropertyType])
  @nestAccessControl.UseRoles({
    resource: "PropertyType",
    action: "read",
    possession: "any",
  })
  async propertyTypes(
    @graphql.Args() args: PropertyTypeFindManyArgs
  ): Promise<PropertyType[]> {
    return this.service.propertyTypes(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => PropertyType, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "PropertyType",
    action: "read",
    possession: "own",
  })
  async propertyType(
    @graphql.Args() args: PropertyTypeFindUniqueArgs
  ): Promise<PropertyType | null> {
    const result = await this.service.propertyType(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => PropertyType)
  @nestAccessControl.UseRoles({
    resource: "PropertyType",
    action: "create",
    possession: "any",
  })
  async createPropertyType(
    @graphql.Args() args: CreatePropertyTypeArgs
  ): Promise<PropertyType> {
    return await this.service.createPropertyType({
      ...args,
      data: args.data,
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => PropertyType)
  @nestAccessControl.UseRoles({
    resource: "PropertyType",
    action: "update",
    possession: "any",
  })
  async updatePropertyType(
    @graphql.Args() args: UpdatePropertyTypeArgs
  ): Promise<PropertyType | null> {
    try {
      return await this.service.updatePropertyType({
        ...args,
        data: args.data,
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => PropertyType)
  @nestAccessControl.UseRoles({
    resource: "PropertyType",
    action: "delete",
    possession: "any",
  })
  async deletePropertyType(
    @graphql.Args() args: DeletePropertyTypeArgs
  ): Promise<PropertyType | null> {
    try {
      return await this.service.deletePropertyType(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [Property], { name: "dynamicPropertyInstances" })
  @nestAccessControl.UseRoles({
    resource: "Property",
    action: "read",
    possession: "any",
  })
  async findDynamicPropertyInstances(
    @graphql.Parent() parent: PropertyType,
    @graphql.Args() args: PropertyFindManyArgs
  ): Promise<Property[]> {
    const results = await this.service.findDynamicPropertyInstances(
      parent.id,
      args
    );

    if (!results) {
      return [];
    }

    return results;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => [ObjectType], { name: "objectTypes" })
  @nestAccessControl.UseRoles({
    resource: "ObjectType",
    action: "read",
    possession: "any",
  })
  async findObjectTypes(
    @graphql.Parent() parent: PropertyType,
    @graphql.Args() args: ObjectTypeFindManyArgs
  ): Promise<ObjectType[]> {
    const results = await this.service.findObjectTypes(parent.id, args);

    if (!results) {
      return [];
    }

    return results;
  }
}
