/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { PropertyTypeService } from "../propertyType.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { PropertyTypeCreateInput } from "./PropertyTypeCreateInput";
import { PropertyType } from "./PropertyType";
import { PropertyTypeFindManyArgs } from "./PropertyTypeFindManyArgs";
import { PropertyTypeWhereUniqueInput } from "./PropertyTypeWhereUniqueInput";
import { PropertyTypeUpdateInput } from "./PropertyTypeUpdateInput";
import { PropertyFindManyArgs } from "../../property/base/PropertyFindManyArgs";
import { Property } from "../../property/base/Property";
import { PropertyWhereUniqueInput } from "../../property/base/PropertyWhereUniqueInput";
import { ObjectTypeFindManyArgs } from "../../objectType/base/ObjectTypeFindManyArgs";
import { ObjectType } from "../../objectType/base/ObjectType";
import { ObjectTypeWhereUniqueInput } from "../../objectType/base/ObjectTypeWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class PropertyTypeControllerBase {
  constructor(
    protected readonly service: PropertyTypeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: PropertyType })
  @nestAccessControl.UseRoles({
    resource: "PropertyType",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createPropertyType(
    @common.Body() data: PropertyTypeCreateInput
  ): Promise<PropertyType> {
    return await this.service.createPropertyType({
      data: data,
      select: {
        createdAt: true,
        id: true,
        schema: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [PropertyType] })
  @ApiNestedQuery(PropertyTypeFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "PropertyType",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async propertyTypes(@common.Req() request: Request): Promise<PropertyType[]> {
    const args = plainToClass(PropertyTypeFindManyArgs, request.query);
    return this.service.propertyTypes({
      ...args,
      select: {
        createdAt: true,
        id: true,
        schema: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: PropertyType })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PropertyType",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async propertyType(
    @common.Param() params: PropertyTypeWhereUniqueInput
  ): Promise<PropertyType | null> {
    const result = await this.service.propertyType({
      where: params,
      select: {
        createdAt: true,
        id: true,
        schema: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: PropertyType })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PropertyType",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updatePropertyType(
    @common.Param() params: PropertyTypeWhereUniqueInput,
    @common.Body() data: PropertyTypeUpdateInput
  ): Promise<PropertyType | null> {
    try {
      return await this.service.updatePropertyType({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          schema: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: PropertyType })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "PropertyType",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deletePropertyType(
    @common.Param() params: PropertyTypeWhereUniqueInput
  ): Promise<PropertyType | null> {
    try {
      return await this.service.deletePropertyType({
        where: params,
        select: {
          createdAt: true,
          id: true,
          schema: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/dynamicPropertyInstances")
  @ApiNestedQuery(PropertyFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Property",
    action: "read",
    possession: "any",
  })
  async findDynamicPropertyInstances(
    @common.Req() request: Request,
    @common.Param() params: PropertyTypeWhereUniqueInput
  ): Promise<Property[]> {
    const query = plainToClass(PropertyFindManyArgs, request.query);
    const results = await this.service.findDynamicPropertyInstances(params.id, {
      ...query,
      select: {
        createdAt: true,

        dynamicProperty: {
          select: {
            id: true,
          },
        },

        id: true,

        object: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
        value: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/dynamicPropertyInstances")
  @nestAccessControl.UseRoles({
    resource: "PropertyType",
    action: "update",
    possession: "any",
  })
  async connectDynamicPropertyInstances(
    @common.Param() params: PropertyTypeWhereUniqueInput,
    @common.Body() body: PropertyWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      dynamicPropertyInstances: {
        connect: body,
      },
    };
    await this.service.updatePropertyType({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/dynamicPropertyInstances")
  @nestAccessControl.UseRoles({
    resource: "PropertyType",
    action: "update",
    possession: "any",
  })
  async updateDynamicPropertyInstances(
    @common.Param() params: PropertyTypeWhereUniqueInput,
    @common.Body() body: PropertyWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      dynamicPropertyInstances: {
        set: body,
      },
    };
    await this.service.updatePropertyType({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/dynamicPropertyInstances")
  @nestAccessControl.UseRoles({
    resource: "PropertyType",
    action: "update",
    possession: "any",
  })
  async disconnectDynamicPropertyInstances(
    @common.Param() params: PropertyTypeWhereUniqueInput,
    @common.Body() body: PropertyWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      dynamicPropertyInstances: {
        disconnect: body,
      },
    };
    await this.service.updatePropertyType({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/objectTypes")
  @ApiNestedQuery(ObjectTypeFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ObjectType",
    action: "read",
    possession: "any",
  })
  async findObjectTypes(
    @common.Req() request: Request,
    @common.Param() params: PropertyTypeWhereUniqueInput
  ): Promise<ObjectType[]> {
    const query = plainToClass(ObjectTypeFindManyArgs, request.query);
    const results = await this.service.findObjectTypes(params.id, {
      ...query,
      select: {
        PropertyTypes: {
          select: {
            id: true,
          },
        },

        createdAt: true,

        eventTypes: {
          select: {
            id: true,
          },
        },

        id: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/objectTypes")
  @nestAccessControl.UseRoles({
    resource: "PropertyType",
    action: "update",
    possession: "any",
  })
  async connectObjectTypes(
    @common.Param() params: PropertyTypeWhereUniqueInput,
    @common.Body() body: ObjectTypeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      objectTypes: {
        connect: body,
      },
    };
    await this.service.updatePropertyType({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/objectTypes")
  @nestAccessControl.UseRoles({
    resource: "PropertyType",
    action: "update",
    possession: "any",
  })
  async updateObjectTypes(
    @common.Param() params: PropertyTypeWhereUniqueInput,
    @common.Body() body: ObjectTypeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      objectTypes: {
        set: body,
      },
    };
    await this.service.updatePropertyType({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/objectTypes")
  @nestAccessControl.UseRoles({
    resource: "PropertyType",
    action: "update",
    possession: "any",
  })
  async disconnectObjectTypes(
    @common.Param() params: PropertyTypeWhereUniqueInput,
    @common.Body() body: ObjectTypeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      objectTypes: {
        disconnect: body,
      },
    };
    await this.service.updatePropertyType({
      where: params,
      data,
      select: { id: true },
    });
  }
}
