/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";

import {
  Prisma,
  PropertyType as PrismaPropertyType,
  Property as PrismaProperty,
  ObjectType as PrismaObjectType,
} from "@prisma/client";

export class PropertyTypeServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count(
    args: Omit<Prisma.PropertyTypeCountArgs, "select">
  ): Promise<number> {
    return this.prisma.propertyType.count(args);
  }

  async propertyTypes(
    args: Prisma.PropertyTypeFindManyArgs
  ): Promise<PrismaPropertyType[]> {
    return this.prisma.propertyType.findMany(args);
  }
  async propertyType(
    args: Prisma.PropertyTypeFindUniqueArgs
  ): Promise<PrismaPropertyType | null> {
    return this.prisma.propertyType.findUnique(args);
  }
  async createPropertyType(
    args: Prisma.PropertyTypeCreateArgs
  ): Promise<PrismaPropertyType> {
    return this.prisma.propertyType.create(args);
  }
  async updatePropertyType(
    args: Prisma.PropertyTypeUpdateArgs
  ): Promise<PrismaPropertyType> {
    return this.prisma.propertyType.update(args);
  }
  async deletePropertyType(
    args: Prisma.PropertyTypeDeleteArgs
  ): Promise<PrismaPropertyType> {
    return this.prisma.propertyType.delete(args);
  }

  async findDynamicPropertyInstances(
    parentId: string,
    args: Prisma.PropertyFindManyArgs
  ): Promise<PrismaProperty[]> {
    return this.prisma.propertyType
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .dynamicPropertyInstances(args);
  }

  async findObjectTypes(
    parentId: string,
    args: Prisma.ObjectTypeFindManyArgs
  ): Promise<PrismaObjectType[]> {
    return this.prisma.propertyType
      .findUniqueOrThrow({
        where: { id: parentId },
      })
      .objectTypes(args);
  }
}
